name: ML Pipeline CI

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          ls -R mlruns